# Disabled for now since it was ICEing
# cargo-features = ["codegen-backend"]

[workspace]
resolver = "2"
members = ["tetanes", "tetanes-core"]

[workspace.package]
version = "0.10.0"
rust-version = "1.74.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
readme = "README.md"
documentation = "https://docs.rs/tetanes"
repository = "https://github.com/lukexor/tetanes.git"
homepage = "https://lukeworks.tech/tetanes"

[workspace.dependencies]
anyhow = "1.0"
bincode = "1.3"
cfg-if = "1.0"
clap = { version = "4.5", default-features = false, features = [
  "std",
  "help",
  "usage",
  "suggestions",
  "derive",
] }
dirs = "5.0"
image = { version = "0.24", default-features = false, features = ["png"] }
puffin = "0.19"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.58"
tracing = { version = "0.1", default-features = false, features = [
  "std",
  "release_max_level_warn",
] }
tracing-subscriber = "0.3"
serde_json = "1.0"
web-time = "1.0"

# Playable framerates in development
[profile.dev]
opt-level = 1
# codegen-backend = "cranelift"

[profile.profiling]
inherits = "release"
debug = true

# Profile used by 'cargo dist'
[profile.dist]
inherits = "release"
codegen-units = 1
lto = true
strip = true
panic = 'abort'

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.9.0"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = ["shell", "homebrew", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
]
# Publish jobs to run in CI
pr-run-mode = "plan"
# A GitHub repo to push Homebrew formulas to
tap = "lukexor/formulae"
# Publish jobs to run in CI
publish-jobs = ["homebrew", "./package-macos"]
# Skip checking whether the specified configuration files are up to date
allow-dirty = ["msi"]
