[package]
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
categories = ["emulators", "wasm"]
description = "A NES Emulator written in Rust with WebAssembly support"
documentation = "https://docs.rs/tetanes"
edition = "2021"
keywords = ["nes", "emulator", "wasm"]
license = "MIT OR Apache-2.0"
name = "tetanes"
repository = "https://github.com/lukexor/tetanes.git"
resolver = "2"
version = "0.9.0"
default-run = "tetanes"
exclude = ["/bin", "/static", "/test_roms", "/docs", "/test_results"]

[package.metadata]
msrv = "1.70.0"

[package.metadata.wix]
upgrade-guid = "DB76CEB0-15B8-4727-9C3E-55819AB5E7B9"
path-guid = "5731AE63-80DE-4CD7-ADFA-9E79BEDCE08B"

[dependencies]
anyhow = "1.0"
bincode = "1.3"
bitflags = { version = "2.4", features = ["serde"] }
chrono = "0.4"
cpal = "0.15.2"
crossbeam = "0.8.3"
dirs = "5.0"
enum_dispatch = "0.3"
features = { version = "0.10.0", default-features = false }
flate2 = "1.0"
image = { version = "0.24.7", default-features = false, features = ["png"] }
itertools = "0.12.0"
libc = "0.2"
log = { version = "0.4", features = ["release_max_level_warn", "serde"] }
once_cell = "1.19"
pixels = "0.13.0"
png = { version = "0.17.10", default-features = false }
pretty_env_logger = "0.5"
puffin = "0.18.1"
puffin_http = "0.15.0"
rand = "0.8"
ringbuf = "0.3"
rubato = "0.14.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
winit = { version = "0.29.5", default-features = false, features = [
  "rwh_05",
  "x11",
  "wayland",
  "wayland-dlopen",
  "wayland-csd-adwaita",
  "serde",
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
# Required because of downstream dependencies: https://docs.rs/getrandom/latest/getrandom/#webassembly-support
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"

[features]
default = ["cycle-accurate"]
cycle-accurate = []
profiling = []

# Optimized development for playable framerates
[profile.dev-opt]
inherits = "dev"
opt-level = 1

[profile.test]
inherits = "dev-opt"

[profile.profile]
inherits = "release"
debug = true

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
codegen-units = 1
lto = "thin"

[workspace]
members = ["utils", "web"]

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.4.3"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = ["shell", "homebrew", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
]
# Publish jobs to run in CI
pr-run-mode = "plan"
# A GitHub repo to push Homebrew formulas to
tap = "lukexor/formulae"
# Publish jobs to run in CI
publish-jobs = ["homebrew", "./package-macos"]
# Skip checking whether the specified configuration files are up to date
allow-dirty = ["msi"]
