# Disabled for now since it was ICEing
# cargo-features = ["codegen-backend"]

[workspace]
resolver = "2"
members = ["tetanes", "tetanes-core", "tetanes-utils"]

[workspace.package]
version = "0.10.0"
rust-version = "1.78.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
readme = "README.md"
documentation = "https://docs.rs/tetanes"
repository = "https://github.com/lukexor/tetanes.git"
homepage = "https://lukeworks.tech/tetanes"

[workspace.dependencies]
anyhow = "1.0"
bincode = "1.3"
cfg-if = "1.0"
clap = { version = "4.5", default-features = false, features = [
  "std",
  "help",
  "usage",
  "suggestions",
  "derive",
] }
dirs = "5.0"
image = { version = "0.24", default-features = false, features = ["png"] }
puffin = "0.19"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.58"
tracing = { version = "0.1", default-features = false, features = [
  "std",
  "release_max_level_warn",
] }
tracing-subscriber = "0.3"
serde_json = "1.0"
web-time = "0.2" # FIXME: winit is using an old version

# Playable framerates in development
[profile.dev]
opt-level = 1
# codegen-backend = "cranelift"

[profile.release]
codegen-units = 1
lto = true
# See: https://smallcultfollowing.com/babysteps/blog/2024/05/02/unwind-considered-harmful/
panic = 'abort'

[profile.flamegraph]
inherits = "release"
debug = true

# Profile used by 'cargo dist'
[profile.dist]
strip = true
inherits = "release"

[profile.dev.package.serde]
inherits = "release"
[profile.dev.package.bincode]
inherits = "release"
[profile.dev.build-override]
inherits = "release"

[workspace.metadata.wix]
upgrade-guid = "DB76CEB0-15B8-4727-9C3E-55819AB5E7B9"
path-guid = "5731AE63-80DE-4CD7-ADFA-9E79BEDCE08B"
license = false
eula = false

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.14.1"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "homebrew", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
]
# Publish jobs to run in CI
pr-run-mode = "upload" # TODO: change this back to plan when vetted
# A GitHub repo to push Homebrew formulas to
tap = "lukexor/formulae"
# Publish jobs to run in CI
publish-jobs = ["homebrew", "./package-macos"]
# Skip checking whether the specified configuration files are up to date
allow-dirty = ["msi"]
# Whether to install an updater program
install-updater = true

[workspace.metadata.dist.dependencies.apt]
libgtk-3-dev = '*'
