[package]
name = "tetanes"
version = "0.10.0"
license = "MIT OR Apache-2.0"
description = "A NES Emulator written in Rust with WebAssembly support"
authors = ["Luke Petherbridge <me@lukeworks.tech>"]
readme = "README.md"
documentation = "https://docs.rs/tetanes"
repository = "https://github.com/lukexor/tetanes.git"
homepage = "https://lukeworks.tech/tetanes"
categories = ["emulators", "wasm"]
keywords = ["nes", "emulator", "wasm"]
default-run = "tetanes"
exclude = ["/bin", "/static", "/test_roms", "/docs", "/test_results"]
edition = "2021"

[package.metadata]
msrv = "1.74.0"

[package.metadata.wix]
upgrade-guid = "DB76CEB0-15B8-4727-9C3E-55819AB5E7B9"
path-guid = "5731AE63-80DE-4CD7-ADFA-9E79BEDCE08B"

[lib]
bench = false

[features]
default = ["cycle-accurate"]
profiling = ["dep:puffin", "dep:puffin_egui"]
console_log = ["dep:console_log", "dep:console_error_panic_hook"]
cycle-accurate = []

[dependencies]
anyhow = "1.0"
bincode = "1.3"
bitflags = { version = "2.4", features = ["serde"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
clap = { version = "4.5", features = ["derive"] }
crossbeam = "0.8"
dirs = "5.0"
egui = { version = "0.26", features = ["rayon"] }
egui-winit = "0.26"
egui-wgpu = "0.26"
enum_dispatch = "0.3"
flate2 = "1.0"
image = { version = "0.24", default-features = false, features = ["png"] }
log = { version = "0.4", features = ["release_max_level_warn"] }
once_cell = "1.19"
# TODO: Update when new version is released with updated winit version to 0.29
pixels = { git = "https://github.com/mkrasnitski/pixels/", branch = "bump-wgpu-winit" }
puffin = { version = "0.19", optional = true }
puffin_egui = { version = "0.26", optional = true }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thingbuf = "0.1"
web-time = "1.0"
winit = { version = "0.29", features = ["serde"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cpal = "0.15"
pollster = "0.3"
pretty_env_logger = "0.5"
rfd = "0.13"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = { version = "0.1", optional = true }
console_log = { version = "1.0", features = ["color"], optional = true }
cpal = { version = "0.15", features = ["wasm-bindgen"] }
# Required because of downstream dependencies: https://docs.rs/getrandom/latest/getrandom/#webassembly-support
getrandom = { version = "0.2", features = ["js"] }
puffin = { version = "0.19", features = ["web"], optional = true }
web-sys = { version = "0.3", features = ["Window", "Document", "HtmlElement"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "nes"
harness = false

# Playable framerates in development
[profile.dev]
opt-level = 1

[profile.profiling]
inherits = "release"
debug = true

# Profile used by 'cargo dist'
[profile.dist]
codegen-units = 1
inherits = "release"
lto = "thin"
strip = true

[profile.dist-web]
inherits = "dist"
panic = "abort"

[workspace]
members = ["utils", "run-wasm"]

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.9.0"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = ["shell", "homebrew", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
]
# Publish jobs to run in CI
pr-run-mode = "plan"
# A GitHub repo to push Homebrew formulas to
tap = "lukexor/formulae"
# Publish jobs to run in CI
publish-jobs = ["homebrew", "./package-macos"]
# Skip checking whether the specified configuration files are up to date
allow-dirty = ["msi"]
