# [unstable]
# codegen-backend = true

# [profile.dev]
# codegen-backend = "cranelift"

[build]
rustflags = ["-Z", "threads=8", "-C", "target-cpu=native"]

[target.'cfg(target_arch = "wasm32")']
rustflags = [
  "-Z",
  "threads=8",
  "-C",
  "panic=abort",
  "--cfg=web_sys_unstable_apis",
]
