[alias]
run-wasm = "run --release --package run-wasm --"

[build]
rustflags = ["-Z", "threads=8", "-C", "target-cpu=native"]

[target.'cfg(target_arch = "wasm32")']
rustflags = ["-Z", "threads=8", "--cfg=web_sys_unstable_apis"]
