[package]
name = "tetanes-core"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
description = "A NES Emulator written in Rust"
authors.workspace = true
readme.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true
categories = ["emulators"]
keywords = ["nes", "emulator"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["cycle-accurate"]
cycle-accurate = []

[dependencies]
anyhow.workspace = true
bincode.workspace = true
bitflags = { version = "2.4", features = ["serde"] }
enum_dispatch = "0.3"
rand = "0.8"
serde.workspace = true
tracing.workspace = true
tetanes-util = { path = "../tetanes-util" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dirs.workspace = true

[dev-dependencies]
serde_json.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "clock_frame"
harness = false
