[package]
name = "tetanes-core"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
description = "A NES Emulator written in Rust"
authors.workspace = true
readme.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true
categories = ["emulators"]
keywords = ["nes", "emulator"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["cycle-accurate"]
profiling = ["dep:puffin"]
cycle-accurate = []

[dependencies]
anyhow.workspace = true
bincode.workspace = true
bitflags = { version = "2.4", features = ["serde"] }
cfg-if.workspace = true
dirs.workspace = true
enum_dispatch = "0.3"
flate2 = "1.0"
rand = "0.8"
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
puffin = { workspace = true, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
puffin = { workspace = true, features = ["web"], optional = true }
web-time.workspace = true

[dev-dependencies]
image.workspace = true
serde_json.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "clock_frame"
harness = false
