---
name: Release PR

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]

permissions:
  pull-requests: write
  contents: write

jobs:
  release-pr:
    name: Release PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: |
          sudo apt update
          sudo apt install -y libudev-dev libasound2-dev
      - name: Run release
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
